### ISSUE TITLE
Navabr

### ISSUE THREAD

**Issue by 0m3ga13** [202306-NEA-DZ-FEW/student-store-team-2#19]
**Task title**
Create a functional Navbar

**Task description**
Create a functional navbar, that cpntains:
- Logo
- Home Button
- Products Button
- Order Page
- Profile Button
- Search Button
ensure responsiveness as well

**Subtasks**
- [ ] Create Search Bar
- [x] Create Profile Button
- [x] Populate the Navbar

**Screenshots**
![image](https://github.com/202306-NEA-DZ-FEW/student-store-team-2/assets/62702326/b3ee3b30-b7a6-4ad6-8ce9-8e0148b714cb)

**Link to the component on Figma**
[Figma Link
](https://www.figma.com/file/FYZIsFvg1rLu50UnriUN8Y/Student-Store-Project?type=design&node-id=0-1&mode=design&t=0DdQfVRHQ85SzzLb-0)
[Additional Resource](https://github.com/202306-NEA-DZ-FEW/e-commerce-project-magnimarket/blob/main/src/components/Navbar/Navbar.jsx)
